---
- name: configuration
  hosts: all
  gather_facts: false # remove later! speeds up testing
  become: true
  tasks:
  - include_role:
      name: common

- name: deploy haproxy
  hosts: frontends
  gather_facts: false # remove later! speeds up testing
  become: true
  tasks:
  - include_role:
      name: frontends

- name: deploy application servers
  hosts: apps
  gather_facts: false
  become: true
  tasks:
    - include_role: 
        name: apps

- name: deploy postgres database
  gather_facts: false
  become: true
  hosts: appdbs
  tasks:
    - include_role: 
        name: database
