- name: install postgres
  yum:
    name: postgresql-server
    state: latest

- name: start postgres
  service:
    name: postgresql.service
    enabled: yes

- name: check if /var/lib/pgsql/data/PG_VERSION exist
  stat: 
    path: /var/lib/pgsql/data/PG_VERSION
  register: stat_results

- name: initilize postgres
  command: postgresql-setup initdb
  when: stat_results.stat.exists == False
- name: initilize postgres some more
  command: chkconfig postgresql on
  when: stat_results.stat.exists == False

- name: start postgres
  service:
    name: postgresql.service
    state: started
    enabled: yes


